#!/bin/bash
sudo pacman -S chromium dconf-editor faenza-icon-theme gvfs lxde leafpad lightdm lightdm-gtk-greeter mate-accountsdialog ncdu networkmanager networkmanager-dispatcher-ntpd network-manager-applet ntp numix-themes parcellite thunar thunar-volman thunar-archive-plugin tumbler ttf-liberation udisks xdotool xfce4-panel xdg-user-dirs-gtk zip unrar unzip p7zip --noconfirm
