#!/bin/bash
sudo pacman -S haveged
sudo systemctl enable haveged
sudo systemctl start haveged
sudo pacman-key --init
sudo pacman-key --populate archlinux
sudo pacman -Syy
sudo pacman -S accountsservice arandr activity-log-manager cantarell-fonts dconf-editor dosfstools faenza-icon-theme gnome-disk-utility gamin gnome-keyring gparted gvfs lxde leafpad lightdm lightdm-gtk-greeter mate-accountsdialog ncdu networkmanager ntfs-3g pavucontrol polkit-gnome pulseaudio python2-xdg networkmanager-dispatcher-ntpd network-manager-applet ntp numlockx numix-themes parcellite screenlets screenlets-pack-basic thunar thunar-volman thunar-archive-plugin tumbler ttf-liberation udisks xdotool xfce4-notifyd xfce4-panel xfce4-power-manager xdg-user-dirs-gtk xscreensaver youtube-dl zip unrar unzip p7zip --noconfirm
xdg-user-dirs-update
sudo updatedb
sudo systemctl enable lightdm
sudo systemctl enable ntpd
sudo systemctl enable NetworkManager
rm -r .config
rm -r .local
cp -r linuxgt/.config .config
cp -r linuxgt/.local .local
cp -r linuxgt/.bashrc .bashrc
cp -r linuxgt/Desktop/Documentation Desktop
chmod +x linuxgt/aur_ins
dialog --title 'Message' --msgbox "Dont't forget to edit /etc/make.conf before running aur_ins (optinal) edit /etc/systemd/journald.conf" 7 65