#!/bin/bash
sudo fc-cache -vf
sudo gtk-update-icon-cache /usr/share/icons/Numix
sudo gtk-update-icon-cache /usr/share/icons/Numix-Circle-Light
sudo gtk-update-icon-cache /usr/share/icons/Numix-Circle
sudo gtk-update-icon-cache /usr/share/icons/Numix-Light
sudo gtk-update-icon-cache /usr/share/icons/hicolor
sudo gtk-update-icon-cache /usr/share/icons/HighContrast

sudo pacman -Scc
